# Advanced monitoring stack installation
---

- name: Configure Loki
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/loki.yml"
  when: "'loki' in services"

- name: Configure AlertManager
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/alertmanager.yml"
  when: "'alertmanager' in services"

- name: Configure Blackbox Exporter
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/blackbox_exporter.yml"
  when: "'blackbox_exporter' in services"

- name: Configure Promtail
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/promtail.yml"
  when: "'promtail' in services"

- name: Update Prometheus configuration with new exporters
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/prometheus.yml"
  when: "'prometheus' in services"
