# Monitoring stack specific configuration
---

# Prometheus configuration
prometheus:
  version: "2.45.0"
  port: 9090
  retention_time: "30d"
  retention_size: "5GB"
  scrape_interval: "15s"
  evaluation_interval: "15s"
  
  # Scrape targets
  targets:
    - job_name: "prometheus"
      static_configs:
        - targets: ["localhost:9090"]
    
    - job_name: "node"
      static_configs:
        - targets:
          - "192.168.0.207:9100"  # plex
          - "192.168.0.132:9100"  # qbittorrent
          - "192.168.0.243:9100"  # grafana
          - "192.168.0.15:9100"   # immich
          - "192.168.0.5:9100"    # fileserver
    
    - job_name: "proxmox"
      static_configs:
        - targets: ["192.168.0.6:9221"]  # pve-exporter
    
    - job_name: "blackbox"
      static_configs:
        - targets: ["192.168.0.202:9115"]  # blackbox-exporter
    
    - job_name: "loki"
      static_configs:
        - targets: ["192.168.0.200:3100"]  # loki
    
    - job_name: "alertmanager"
      static_configs:
        - targets: ["192.168.0.201:9093"]  # alertmanager
        
    # Blackbox probes for external monitoring
    - job_name: "blackbox_http"
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - "http://192.168.0.15:2283"    # immich
          - "http://192.168.0.207:32400"  # plex
          - "http://192.168.0.243:3000"   # grafana
          - "http://192.168.0.5:9090"     # cockpit
          - "http://192.168.0.124"        # ntfy
          - "http://192.168.0.181:3001"   # uptime-kuma
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: "192.168.0.202:9115"  # blackbox exporter

# Grafana configuration
grafana:
  version: "10.0.0"
  port: 3000
  admin_user: admin
  admin_password: "" # Set via vault
  
  # Data sources
  datasources:
    - name: "Prometheus"
      type: "prometheus"
      url: "http://prometheus:9090"
      access: "proxy"
      is_default: true
    - name: "Loki"
      type: "loki"
      url: "http://192.168.0.200:3100"
      access: "proxy"
      is_default: false
  
  # Dashboard provisioning
  dashboards:
    - name: "Node Exporter"
      dashboard_id: 1860
    - name: "Proxmox VE"  
      dashboard_id: 10347
    - name: "Container Monitoring"
      dashboard_id: 893

# Uptime Kuma configuration
uptimekuma:
  port: 3001
  data_dir: "/app/data"
  
  # Monitors to configure
  monitors:
    - name: "Plex"
      url: "http://192.168.0.207:32400/web"
      type: "http"
      interval: 60
    - name: "Grafana"
      url: "http://192.168.0.243:3000"
      type: "http"  
      interval: 60
    - name: "Immich"
      url: "http://192.168.0.15:2283"
      type: "http"
      interval: 60
    - name: "Fileserver Cockpit"
      url: "http://192.168.0.5:9090"
      type: "http"
      interval: 60

# Glance dashboard configuration
glance:
  port: 61208
  title: "Homelab Dashboard"
  theme: "dark"
  
  # Widget configuration
  widgets:
    - type: "system-info"
      title: "System Information"
    - type: "services"
      title: "Critical Services"
      services:
        - name: "Plex"
          url: "http://192.168.0.207:32400"
        - name: "Immich"
          url: "http://192.168.0.15:2283"
        - name: "Fileserver"
          url: "http://192.168.0.5:9090"

# Node Exporter configuration
node_exporter:
  version: "1.6.0"
  port: 9100
  enabled_collectors:
    - "systemd"
    - "processes"
    - "filesystem"
    - "diskstats"
    - "netstat"
    - "meminfo"
    - "loadavg"
    - "cpu"

# Loki log aggregation configuration
loki:
  version: "2.9.0"
  port: 3100
  grpc_port: 9095
  retention_period: "744h"  # 31 days
  
  # Storage configuration
  storage:
    filesystem:
      directory: "/loki/chunks"
    boltdb_shipper:
      active_index_directory: "/loki/boltdb-shipper-active"
      cache_location: "/loki/boltdb-shipper-cache"
      
  # Limits configuration
  limits:
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32
    max_cache_freshness_per_query: "10m"
    max_concurrent_tail_requests: 10

# Alert Manager configuration
alertmanager:
  version: "0.25.0"
  port: 9093
  cluster_port: 9094
  data_retention: "120h"
  
  # Route configuration
  routes:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: "10s"
    group_interval: "10s"
    repeat_interval: "1h"
    receiver: "homelab-notifications"
    
  # Receivers configuration
  receivers:
    - name: "homelab-notifications"
      webhook_configs:
        - url: "http://192.168.0.124/homelab-critical"
          title: "🚨 {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"
          send_resolved: true

# Blackbox Exporter configuration
blackbox_exporter:
  version: "0.24.0"
  port: 9115
  
  # Probe modules
  modules:
    http_2xx:
      prober: "http"
      timeout: "5s"
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        valid_status_codes: [200, 301, 302]
        method: "GET"
        
    tcp_connect:
      prober: "tcp"
      timeout: "5s"
      
    icmp:
      prober: "icmp"
      timeout: "5s"
      icmp:
        preferred_ip_protocol: "ip4"

# Promtail log shipping configuration  
promtail:
  version: "2.9.0"
  port: 9080
  loki_url: "http://192.168.0.200:3100"
  
  # Scrape configurations
  scrape_configs:
    - job_name: "system_logs"
      static_configs:
        - targets: ["localhost"]
          labels:
            job: "system_logs"
            __path__: "/var/log/*.log"
            
    - job_name: "docker_logs"
      static_configs:
        - targets: ["localhost"]
          labels:
            job: "docker_logs"
            __path__: "/docker/*/logs/*.log"