# Advanced monitoring handlers
---

- name: restart loki
  systemd:
    name: loki
    state: restarted
  listen: restart loki

- name: restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
  listen: restart alertmanager

- name: restart blackbox_exporter
  systemd:
    name: blackbox_exporter
    state: restarted
  listen: restart blackbox_exporter

- name: restart promtail
  systemd:
    name: promtail
    state: restarted
  listen: restart promtail