# AlertManager installation and configuration
---

- name: Create alertmanager user
  user:
    name: alertmanager
    system: yes
    shell: /bin/false
    home: /var/lib/alertmanager
    create_home: yes

- name: Create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: '0755'
  with_items:
    - /etc/alertmanager
    - /var/lib/alertmanager
    - /var/lib/alertmanager/data

- name: Download AlertManager
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager.version }}/alertmanager-{{ alertmanager.version }}.linux-amd64.tar.gz"
    dest: /tmp/alertmanager.tar.gz
    mode: '0644'

- name: Extract AlertManager
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install AlertManager binaries
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  with_items:
    - { src: "/tmp/alertmanager-{{ alertmanager.version }}.linux-amd64/alertmanager", dest: "/usr/local/bin/alertmanager" }
    - { src: "/tmp/alertmanager-{{ alertmanager.version }}.linux-amd64/amtool", dest: "/usr/local/bin/amtool" }

- name: Create AlertManager configuration
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '0644'
  notify: restart alertmanager

- name: Create AlertManager systemd service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'
  notify: restart alertmanager

- name: Start and enable AlertManager
  systemd:
    name: alertmanager
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/alertmanager.tar.gz
    - "/tmp/alertmanager-{{ alertmanager.version }}.linux-amd64"