# Blackbox Exporter installation and configuration
---

- name: Create blackbox_exporter user
  user:
    name: blackbox_exporter
    system: yes
    shell: /bin/false
    home: /var/lib/blackbox_exporter
    create_home: yes

- name: Create blackbox_exporter directories
  file:
    path: "{{ item }}"
    state: directory
    owner: blackbox_exporter
    group: blackbox_exporter
    mode: '0755'
  with_items:
    - /etc/blackbox_exporter
    - /var/lib/blackbox_exporter

- name: Download Blackbox Exporter
  get_url:
    url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter.version }}/blackbox_exporter-{{ blackbox_exporter.version }}.linux-amd64.tar.gz"
    dest: /tmp/blackbox_exporter.tar.gz
    mode: '0644'

- name: Extract Blackbox Exporter
  unarchive:
    src: /tmp/blackbox_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install Blackbox Exporter binary
  copy:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter.version }}.linux-amd64/blackbox_exporter"
    dest: /usr/local/bin/blackbox_exporter
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Create Blackbox Exporter configuration
  template:
    src: blackbox.yml.j2
    dest: /etc/blackbox_exporter/blackbox.yml
    owner: blackbox_exporter
    group: blackbox_exporter
    mode: '0644'
  notify: restart blackbox_exporter

- name: Create Blackbox Exporter systemd service
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    mode: '0644'
  notify: restart blackbox_exporter

- name: Start and enable Blackbox Exporter
  systemd:
    name: blackbox_exporter
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/blackbox_exporter.tar.gz
    - "/tmp/blackbox_exporter-{{ blackbox_exporter.version }}.linux-amd64"