# Loki log aggregation installation and configuration
---

- name: Create loki user
  user:
    name: loki
    system: yes
    shell: /bin/false
    home: /var/lib/loki
    create_home: yes

- name: Create loki directories
  file:
    path: "{{ item }}"
    state: directory
    owner: loki
    group: loki
    mode: '0755'
  with_items:
    - /etc/loki
    - /var/lib/loki
    - /loki/chunks
    - /loki/boltdb-shipper-active
    - /loki/boltdb-shipper-cache

- name: Download Loki
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ loki.version }}/loki-linux-amd64.zip"
    dest: /tmp/loki.zip
    mode: '0644'

- name: Extract Loki
  unarchive:
    src: /tmp/loki.zip
    dest: /tmp
    remote_src: yes

- name: Install Loki binary
  copy:
    src: /tmp/loki-linux-amd64
    dest: /usr/local/bin/loki
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Create Loki configuration
  template:
    src: loki.yml.j2
    dest: /etc/loki/loki.yml
    owner: loki
    group: loki
    mode: '0644'
  notify: restart loki

- name: Create Loki systemd service
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    mode: '0644'
  notify: restart loki

- name: Start and enable Loki
  systemd:
    name: loki
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/loki.zip
    - /tmp/loki-linux-amd64