# Promtail log shipping installation and configuration
---

- name: Create promtail user
  user:
    name: promtail
    system: yes
    shell: /bin/false
    home: /var/lib/promtail
    create_home: yes

- name: Create promtail directories
  file:
    path: "{{ item }}"
    state: directory
    owner: promtail
    group: promtail
    mode: '0755'
  with_items:
    - /etc/promtail
    - /var/lib/promtail
    - /var/lib/promtail/positions

- name: Download Promtail
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ promtail.version }}/promtail-linux-amd64.zip"
    dest: /tmp/promtail.zip
    mode: '0644'

- name: Extract Promtail
  unarchive:
    src: /tmp/promtail.zip
    dest: /tmp
    remote_src: yes

- name: Install Promtail binary
  copy:
    src: /tmp/promtail-linux-amd64
    dest: /usr/local/bin/promtail
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Create Promtail configuration
  template:
    src: promtail.yml.j2
    dest: /etc/promtail/promtail.yml
    owner: promtail
    group: promtail
    mode: '0644'
  notify: restart promtail

- name: Create Promtail systemd service
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    mode: '0644'
  notify: restart promtail

- name: Start and enable Promtail
  systemd:
    name: promtail
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/promtail.zip
    - /tmp/promtail-linux-amd64