# Docker installation and configuration
---

- name: Install Docker dependencies
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == "Debian"
  tags: docker

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == "Debian"
  tags: docker

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == "Debian"
  tags: docker

- name: Install Docker Engine
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  tags: docker

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker.compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  tags: docker

- name: Create Docker daemon configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart docker
  tags: docker

- name: Create Docker data directory
  file:
    path: "{{ docker.data_root }}"
    state: directory
    mode: '0755'
  tags: docker

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: docker

- name: Add root to docker group
  user:
    name: root
    groups: docker
    append: yes
  tags: docker